baseurl: "https://vingenuity.github.io/"
languageCode: "en-us"
title: "Vingenuity"
theme: "hugo-materialized"

params:
  owner:
    name: "Vincent Kocks"
    description: "Game Programmer"
    emailAddress: "vincent@vingenuity.net"
    gitHubUsername: "vingenuity"
    linkedInSlug: "vingenuity"
    skypeUsername: "vingenuity"

  sideNav:
    backgroundColor: blue darken-4
    header:
      backgroundImage: "/images/vingenuity-logo.png"
      iconColor: white
      iconSize: lg
      textColor: white
    menu:
      useIcons: true
      iconColor: white
      iconSize: 2x
      textColor: white
      icons:
        project: wrench
        post: edit
        resume: paperclip
  
  developer_titles:
    artist: "Artist"
    designer: "Designer"
    producer: "Producer"
    programmer: "Programmer"
    qa: "QA Tester"
  
