baseurl: "https://vingenuity.github.io/"
languageCode: "en-us"
title: "Vingenuity"
theme: "hugo-materialized"
  
menu:
  main:
    - identifier: home
      icon: home
      name: Home
      url: /
      weight: 100
    - identifier: project
      icon: wrench
      name: Projects
      url: /project/
      weight: 200
    - identifier: post
      name: Posts
      url: /post/
      weight: 300
    - identifier: resume
      name: Resume
      url: /resume/
      weight: 400
    - identifier: work_samples
      name: Work Samples
      url: /work-sample/
      weight: 500

params:
  creationYear: 2014

  owner:
    name: "Vincent Kocks"
    description: "Game Programmer"
    emailAddress: "vincent@vingenuity.net"
    gitHubUsername: "vingenuity"
    linkedInSlug: "vingenuity"
    skypeUsername: "vingenuity"
    vimeoSlug: "vingenuity"

  sideNav:
    backgroundColor: blue darken-4
    header:
      backgroundImage: "/images/vingenuity-logo.png"
      iconColor: white
      iconSize: lg
      textColor: white
    menu:
      iconColor: white
      iconSize: 2x
      textColor: white
      icons:
        home: home
        project: wrench
        post: edit
        resume: paperclip
        work_samples: briefcase

  topNav:
    backgroundColor: blue darken-4
    logo: "/images/vingenuity-logo.png"
    text: "Vingenuity"

  developer_titles:
    artist: "Artist"
    designer: "Designer"
    producer: "Producer"
    programmer: "Programmer"
    qa: "QA Tester"
