baseurl: "https://vingenuity.github.io/"
languageCode: "en-us"
title: "Vingenuity"
theme: "hugo-materialized"

params:
  description: "Game Programmer"
  name: "Vincent Kocks"
  ownerEmailAddress: "vincent@vingenuity.net"
  ownerGitHubUsername: "vingenuity"
  ownerTwitterUsername: "kvingenuity"
  sidenav: "/images/vingenuity-logo.png"
  
  developer_titles:
    artist: "Artist"
    designer: "Designer"
    producer: "Producer"
    programmer: "Programmer"
    qa: "QA Tester"
  
