baseurl: "https://vingenuity.github.io/"
languageCode: "en-us"
title: "Vingenuity"
theme: "hugo-materialized"

params:
  description: "Game Programmer"
  name: "Vincent Kocks"
  ownerEmailAddress: "vincent@vingenuity.net"
  ownerGitHubUsername: "vingenuity"
  ownerTwitterUsername: "kvingenuity"

  sideNav:
    backgroundColor: blue darken-4
    header:
      backgroundImage: "/images/vingenuity-logo.png"
      iconColor: white
      textColor: white
    menu:
      useIcons: true
      iconColor: white
      textColor: white
      icons:
        post: border_color
        project: build
        resume: description
  
  developer_titles:
    artist: "Artist"
    designer: "Designer"
    producer: "Producer"
    programmer: "Programmer"
    qa: "QA Tester"
  
